name: Cities I have been to website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.3.0
        
      - name: Build Angular Application
        run: |
          ls
          npm install -g @angular/cli
          npm install
          ng build
          
      - name: Copy to S3 Bucket
        if: success()
        run: |
          
          aws s3 cp ./dist/cities-i-have-been-to/browser s3://bucketforcity --debug
